### ISSUE TITLE
This example bears very little relation to the quickstart. 

### ISSUE THREAD

**Issue by jeacott1** [auth0/auth0-spring-security-mvc#1]
this example doesnt use the <artifactId>spring-security-auth0</artifactId> as described in the quickstart,
 it munges a bunch of stuff together making it quite painful to tease out what's in each lib and whats been added as 'extra' helpers etc here. 

I want to see:
1. a useful spring-boot-mvc-security-auth0 example that works as a stateless backend for a static spa.
2. I'd like to see recommended best practice for spring-security-auth0 when I want to provide more options than a single /secured/** path. preferably as xml and annotation config.
3. I'd like to see examples of how to access the Principal and their details when using stateless spring-security-auth0

Cheers

**Comment by arcseldon** [comment]
@jeacott1 - for a stateless API to your SPA app, please take a look at:  [auth0-spring-security-api](https://github.com/auth0/auth0-spring-security-api). That repo:

1. Uses `Spring Boot` under the covers - the sessions are stateless - it will recheck the JWT (token) passed on every request for validity to any secured endpoints

2.  It uses 100% Java Annotations / Configuration

3.  You can access the Principal simply by adding it as a method argument to the Controller endpoint - Ironically there is also an example of doing this in this repo - see [here](https://github.com/auth0/auth0-spring-security-mvc/blob/master/examples/auth0-spring-security-mvc-sample/src/main/java/com/auth0/example/HomeController.java)

Your feedback is appreciated - in fact this repo was only published yesterday and has not yet been deployed to Maven etc - it is work in progress this week to bring the samples / the API itself - together with updated dependencies (the library it uses internally is also being updated), and to ensure we have complete documentation for you.

Please feedback any further questions (caveat what I have just said) - and if something is missing I'll aim to fill in the gaps for you.

**Comment by arcseldon** [comment]
@jeacott1 - for this application, have now provided a sample configuration that demonstrates exactly how to achieve point 2). in your list - you can now specify any number of secured endpoints and additionally specify what `roles` or `authorities` you'd like to authorize each with - link to sample config [here](https://github.com/auth0/auth0-spring-security-mvc/blob/master/examples/auth0-spring-security-mvc-sample/src/main/java/com/auth0/example/AppConfig.java)

**Comment by jeacott1** [comment]
neither of those links work.
I have also been looking for examples of how to test these setups. cant seem to figure it out.
how can I use @WithMockUser or similar to test protected endpoints?
