### ISSUE TITLE
Allow setting the auth0.publicKeyPath property to any path, not just the root of the war

### ISSUE THREAD

**Issue by nickptrvc** [auth0/auth0-spring-security-mvc#12]
We have multiple auth0 accounts (e.g. development, staging, and production) and potentially will have multiple auth0 clients setup. In order to user RS256, it requires that we use the `auth0.publicKeyPath` property. This becomes an issue with our configuration because it requires that we ship our application with all of these public keys instead of using some type of configuration management tool. I think it would be best if there was more flexibility in defining this path.

I think not setting the property makes sense that it look in the root path of the war file. Providing a path that doesn't start with / should also start in the root of the war file which I believe it does. But when setting a path that starts with /, I believe it should start at the root of the file system. I haven't been able to successfully do this. It tends to use the root of the war directory and then concats whatever I set the property to.

These examples seem to work fine, for the root of the war directory:
```
auth0.publicKeyPath=myKey.pem
auth0.publicKeyPath=somePath/myKey.pem
```

This is what does not work.
```
auth0.publicKeyPath=/etc/auth0/keys/${spring.profiles.active}.pem

# or this
auth0.publicKeyPath=/etc/auth0/keys/dev.pem
```

**Comment by lbalmaceda** [comment]
@nickptrvc We've discontinued this library but you should be able to achieve a similar result using this one > https://github.com/auth0/auth0-java-mvc-common. It supports RS256 when using a [JWK](https://auth0.com/docs/jwks) Provider implementation. (It could be your own or [ours](https://github.com/auth0/jwks-rsa-java/)). You can find an article explaining how to use it for _Spring Security MVC_ apps with HS256 [here](https://auth0.com/docs/quickstart/webapp/java-spring-security-mvc).  Feel free to drop any issues or feedback in that repo.
Cheers.
