### ISSUE TITLE
Auth0UserDetails getPassword method throws UnsupportedOperationException

### ISSUE THREAD

**Issue by joedunne** [auth0/auth0-spring-security-mvc#6]
In order to use the Spring MVC SwitchUserFilter, the getPassword method in the UserDetails object must return either a valid string or null.

The getPassword method in Auth0UserDetails throws UnsupportedOperationException and cannot be used in the SwitchUserFilter. Please change the method to something like:

    @Override
    public String getPassword() {
        return null;
    }

**Comment by arcseldon** [comment]
@joedunne - thanks for this. Please can you point out the relevant doc links that state the above.

**Comment by joedunne** [comment]
The relevant code is in the SwitchUserFilter.java class, line 343, createSwitchUserToken.

https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/authentication/switchuser/SwitchUserFilter.java

        // create the new authentication token
        targetUserRequest = new UsernamePasswordAuthenticationToken(targetUser, targetUser.getPassword(), newAuths);

**Comment by arcseldon** [comment]
@joedunne - thanks - shall update to return `null` rather than throw `UnsupportedOperationException`.

**Comment by arcseldon** [comment]
The required changes have been merged as PR - awaiting publication to Maven - shall be in next release.

**Comment by arcseldon** [comment]
available with version 1.2.0
