### ISSUE TITLE
The stored token in SessionUtils causes continual re-authentication

### ISSUE THREAD

**Issue by joedunne** [auth0/auth0-spring-security-mvc#7]
After Authentication please clear the stored tokens in SessionUtils.

SessionUtils.setTokens(req, null);

If this is not done the user is re-authenticated on every request. Further this is necessary for the Spring SwitchUserFilter to work.

**Comment by arcseldon** [comment]
@joedunne - do you have a git repo you can share illustrating your issues with switchUserFilter?

**Comment by joedunne** [comment]
No I do not have a git repo that I can share with you. However you can test by simply placing a break point in the Auth0AuthenticationFilter.doFilter method where it calls  authenticationManager.authenticate(token).

I fixed it by making the following change to the Auth0JWTToken class:

    /**
     * Checks the {@code credentials}, {@code principal} and {@code details} objects, invoking the
     * {@code eraseCredentials} method on any which implement {@link CredentialsContainer}.
     */
    public void eraseCredentials() {
        super.eraseCredentials();
        final ServletRequestAttributes servletReqAttr = (ServletRequestAttributes) RequestContextHolder.currentRequestAttributes();
        final HttpServletRequest req = servletReqAttr.getRequest();
       //Clear out the SessionUtils token to avoid continual re-authentication
        SessionUtils.setTokens(req, null);
    }

**Comment by arcseldon** [comment]
@joedunne - have completed a PR that addresses the issue of full re-authentication on every request. However, removing the Tokens is not an option - every request still depends on JWT Verification - the underlying user principal however is not re-written on each request if an authentication already exists.  Shall be in next release once published to Maven.

**Comment by joedunne** [comment]
Thank you!

**Comment by arcseldon** [comment]
available with version 1.2.0
